name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Cada push a main hará deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build  # Solo build, no gh-pages aquí

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # La carpeta generada por next export / output: 'export'
          publish_branch: gh-pages
